### PR TITLE
CertifedBoosts, getBoostRecipients, and BoostCredentials

### PR DESCRIPTION
**Pull request by Custard7**
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=-uxFkMC)
# Overview

#### 💡 Feature Breakdown (screenshots & videos encouraged!)

- Updates LCN Brain to wrap VCs in a `CertifiedBoost` VC when using `sendBoost`, and verifying that the VCs use the boostId, and verify that the sender is authorized to issue the boost + that the credential matches the boost credential.
- Updates LCN Plugin to append boostId to a boost VC when calling `sendBoost()`
- Adds `getBoostRecipients` function to LCN Brain + LCN Plugin so you can retrieve a list of boost recipients
- Adds new `boost` type to `learnCard.invoke.newCredential({ type: 'boost' })` to VC Templates Plugin
- Adds new VC Verification plugin, extending `learnCard.invoke.verifyCredential()` so it will verify a CertifiedBoost VC with a registry of trusted CertifiedBoost verifiers 
- Add tests for LCN Plugin + VerifyBoost Plugin
- Add tests for `sendBoost` for LCN Brain
- Add tests for `getBoostRecipients` for LCN Brain

#### 🔍 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore (refactor, documentation update, etc)

#### 💳 Does This Create Any New Technical Debt? ( If yes, please describe and [add JIRA TODOs](https://welibrary.atlassian.net/jira/software/projects/WE/boards/2) )
- [ ] No
- [ ] Yes

# Testing

#### 🧪 Code Coverage

# Documentation

#### 📊 Storybook

# ✅ PR Checklist
- [ ] Related to a Jira issue ([create one if not](https://welibrary.atlassian.net/jira/software/projects/WE/boards/2))
- [x] My code follows **style guidelines** (eslint / prettier)
- [x] I have **manually tested** common end-2-end cases
- [x] I have **reviewed** my code
- [x] I have **commented** my code, particularly where ambiguous
- [x] New and existing **unit tests pass** locally with my changes
- [ ] I have made corresponding changes to **gitbook documentation**

### 🚀 Ready to squash-and-merge?:
- [x] Code is backwards compatible
- [x] There is **not** a "Do Not Merge" label on this PR
- [x] I have thoughtfully considered the security implications of this change.
- [x] This change does not expose new public facing endpoints that do not have authentication

### CODE REVIEW

**Comment by goblincore** [comment]
Screenshot 2023-03-03 at 5 51 54 PM
@Custard7 When I run pnpm test in the brain service directory I get the above error relating to  TypeError: Cannot read properties of undefined (reading 'array'), is that an issue with the test?

**Comment by Custard7** [comment]
@goblincore - hmm, I don't think so. I also just pushed up a ts fix in the brain-service that was causing an issue to build. Am watching the git action test runner to see if it passes too 😎

You may want to try the following:

- `pnpm i` in the root directory, and then `pnpm build` in the root directory

You may need to build each one in order. If so:
- then `pnpm build` in the learn-card-types
- then `pnpm build` in the learn-card-core
- then `pnpm build` in the brain-service
- then `pnpm build` in the brain-client
- then `pnpm build` in the plugins/learn-card-network

Lol, then try running pnpm test in the brain-service.

**Comment by goblincore** [comment]
Cool will do that 👍

**Comment by Custard7** [comment]
@goblincore - any luck? Looks like we are all green on the tests up above when run by git 😎

**Comment by goblincore** [comment]
@Custard7 yeah saw the action running the tests and looks good to me!! locally im good as long as i have a seed set in the env, seems like you did this for github so LGTM

**Review by goblincore — APPROVED** [review]

**Pull request merged**
