### PR TITLE
[LC-158] Certificate Display Card

### PR DESCRIPTION
**Pull request by smurflo2**
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=uZX1IbX)
# Overview

#### 🎟 Relevant Jira Issues

[LC-158](https://welibrary.atlassian.net/browse/LC-158)

#### 📚 What is the context and goal of this PR?
We're introducing a certificate display type for official sorts of uses. What does that mean? NEW UI

- Boosts with certificate display types should now be displayed with a brand new UI
- The outline colors are the category's 500 value
- The background for the back face and the "issuer stamp" (spiky circle thing) should be the category's 700 value
- When viewing the boost there's a ... button that allows you to share your boost
- The boost distinguishes between Self Verified (issued to self), Trusted Verifier (in the [trusted apps registry](https://github.com/learningeconomy/registries/blob/main/learncard/trusted-app-registry.json) with `app.isTrusted` set to true), Unknown Verifier (not in the registry), and Untrusted Verifier (in the registry with `app.isTrusted` set to false
- In the manage boosts tab, the boost will display up to 3 recipients' profile images (with "+X" if applicable)

(Note: Skills related items are not part of this PR)

#### 🥴 TL; RL:
New UI for new boost type!

#### 💡 Feature Breakdown (screenshots & videos encouraged!)
Preview (front side w/ background)
image

Back Side
image

Manage Tab -> multiple recipients
image

Issued, self verified (with ... menu)
image

Untrusted Verifier
image

Trusted Verifier 
image

#### 🔍 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Chore (refactor, documentation update, etc)

#### 💳 Does This Create Any New Technical Debt? ( If yes, please describe and [add JIRA TODOs](https://welibrary.atlassian.net/jira/software/projects/WE/boards/2) )
- [x] No
- [ ] Yes

# Testing

#### 🔬 How Can Someone QA This?

**Use `learncardapp` branch `lc-157`** - these two are very tied together

- Go through the Issue Boost flow and select the Certificate display type (only available for some categories)
- Preview the boost and verify that it all looks good and matches the design / user stories
  - double check that badge display still works fine
- Boosts that are actually issued are a bit trickier since we don't actually store that display type yet. The easiest way to do this is to search for `const isCertificate` in learncardapp and react-learn-card. Then just set all of those to true and everything will appear in certificate display mode
  - components in learncardapp + learn-card-base: BoostManagedCard, BoostPreview, NonBoostPreview, VCDisplayCardWrapper2, VCModal,
  - There's also a displayType condition circa line 153 in VCDisplayCard2 in react-learn-card
- open a bunch of credentials in your wallets. Try all the categories and configurations. Make sure they all look good and work as expected
  - issued credentials should have the ... button
- Go to the Managed tab for a boost you've issued to multiple people. Open that one up, you should see multiple users' profile pics + "Issued to X people"
- Test self verified / trusted verifier / untrusted verifier / unknown verifier
  - You can update the "Kyle Dev" entry however you like
  - `did` and `app.isTrusted` are the relevant fields

#### 🧪 Code Coverage

# Documentation

#### 📊 Storybook

# ✅ PR Checklist
- [x] Related to a Jira issue ([create one if not](https://welibrary.atlassian.net/jira/software/projects/WE/boards/2))
- [x] My code follows **style guidelines** (eslint / prettier)
- [x] I have **manually tested** common end-2-end cases
- [x] I have **reviewed** my code
- [x] I have **commented** my code, particularly where ambiguous
- [ ] New and existing **unit tests pass** locally with my changes
- [ ] I have made corresponding changes to **gitbook documentation**

### 🚀 Ready to squash-and-merge?:
- [x] Code is backwards compatible
- [x] There is **not** a "Do Not Merge" label on this PR
- [x] I have thoughtfully considered the security implications of this change.
- [x] This change does not expose new public facing endpoints that do not have authentication

### CODE REVIEW

**Comment by Custard7** [comment]
@smurflo2 @gerardopar I was trying to test this guy [alongside](https://github.com/WeLibraryOS/learncardapp/pull/311), but am running into a series of TS errors. Is react package building properly for you both?

I went through and fixed a few on my side, but am hitting more:

Screen Shot 2024-04-04 at 6 06 58 PM

**Comment by gerardopar** [comment]
> @smurflo2 @gerardopar I was trying to test this guy [alongside](https://github.com/WeLibraryOS/learncardapp/pull/311), but am running into a series of TS errors. Is react package building properly for you both?
> 
> I went through and fixed a few on my side, but am hitting more:
> 
> Screen Shot 2024-04-04 at 6 06 58 PM

@Custard7 ill look into cleaning some of that up tomorrow

**Comment by Custard7** [comment]
@gerardopar react package builds now, thank you!! ✅

 
Screen Shot 2024-04-05 at 8 37 45 AM

**Review by Custard7 — APPROVED** [review]
Working and looking great to me, matches the figma! ✅

**Pull request merged**
