### PR TITLE
Credential Schemas

### PR DESCRIPTION
**Pull request by TaylorBeeston**
# Overview

#### 📚 What is the context and goal of this PR?
[The CLR Spec](https://www.imsglobal.org/spec/clr/v2p0#verification) mentions that CLRs _must_ have
a `credentialSchema`, and that verifiers _must_ check the schema when verifying

#### 🥴 TL; RL:
Adds support for checking `credentialSchema` as defined in the CLR spec and various specs relating 
to it/referenced by it

#### 💡 Feature Breakdown (screenshots & videos encouraged!)
Most of the work here happened in SSI, and I submitted a PR upstream, so you can read about that [here](https://github.com/spruceid/ssi/pull/520)!

- Fixed a bug where options were not being propagated through plugins when verifying
- Updated the `ProofOptions` type to correctly have the checks that SSI allows, and added `credentialSchema` as one of those checks
- Updated the verification logic in the VC plugin to automatically add `credentialStatus` and/or `credentialSchema` to checks if the incoming VC has the respective fields
    - You can override this by just passing in a different checks array

#### 🛠 Important tradeoffs made:
We are _only_ supporting 1EdTechJSONSchemaValidator2019 schemas for now. I wrote about this in the SSI
PR, but basically it shouldn't be too bad to add support for more in the future, I'm just not super
familiar with what's out there.

Also, it seems adding some of the necessary contexts and syncing with upstream has bloated the WASM
payload up to almost 9 MB now =( Not sure what the best solution is, but maybe someday I can look
at taking some stuff out to lower that, or maybe just adding dynamic context resolution to our fork
and then not inlining so many contexts or something

#### 🔍 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore (refactor, documentation update, etc)

#### 💳 Does This Create Any New Technical Debt? ( If yes, please describe and [add JIRA TODOs](https://welibrary.atlassian.net/jira/software/projects/WE/boards/2) )
- [x] No
- [ ] Yes

# Testing

#### 🔬 How Can Someone QA This?

Open up the CLI, bring in [this bad boy](https://www.imsglobal.org/spec/clr/v2p0#basic-clrcredential) 
and replace the issuer ID with `learnCard.id.did()` (i.e. `vc.issuer.id = learnCard.id.did()`).
Then issue it and verify the resulting credential. You should see `schema` in the checks array!

#### 🧪 Code Coverage

# Documentation

#### 📊 Storybook

# ✅ PR Checklist
- [ ] Related to a Jira issue ([create one if not](https://welibrary.atlassian.net/jira/software/projects/WE/boards/2))
- [x] My code follows **style guidelines** (eslint / prettier)
- [x] I have **manually tested** common end-2-end cases
- [x] I have **reviewed** my code
- [ ] I have **commented** my code, particularly where ambiguous
- [x] New and existing **unit tests pass** locally with my changes
- [ ] I have made corresponding changes to **gitbook documentation**

### 🚀 Ready to squash-and-merge?:
- [x] Code is backwards compatible
- [x] There is **not** a "Do Not Merge" label on this PR
- [x] I have thoughtfully considered the security implications of this change.
- [x] This change does not expose new public facing endpoints that do not have authentication

### CODE REVIEW

**Comment by Custard7** [comment]
@TaylorBeeston - I just tried to running this, and am getting the following error. Do I need to take a specific build step?

Screen Shot 2023-07-19 at 4 20 49 PM

**Comment by TaylorBeeston** [comment]
@Custard7 sometimes NX will cache things it shouldn't so maybe try starting the CLI with `pnx start cli --skip-nx-cache`

**Comment by Custard7** [comment]
@TaylorBeeston 

Hmm, okay I did `pnx start cli --skip-nx-cache`, and now I get this error:

Screen Shot 2023-07-25 at 10 05 05 PM

Although, upon further investigation, 1EdTech just updated the schema from 3.0.1, to 3.0.2 🙈 

Screen Shot 2023-07-25 at 10 07 18 PM

Dangit. So this is probably working for 3.0.1, but I can't test with the 3.0.2 latest CLR schema...

**Comment by TaylorBeeston** [comment]
Omg nice lol. I can add support for 3.0.2 in the morning!

**Comment by Custard7** [comment]
@TaylorBeeston - is this the PR? Let me know if its ready, seems like we still need 3.0.2 and to update with main

**Review by Custard7 — APPROVED** [review]
@TaylorBeeston worked like a charm ✅ 🍀 

Screen Shot 2023-09-20 at 6 28 40 PM

**Comment by Custard7** [comment]
@TaylorBeeston - should we merge this guy in?

**Comment by TaylorBeeston** [comment]
@Custard7 yup! I'm just waiting/watching the context plane stuff first! There was an issue where it didn't want to publish the dynamic loader plugin to npm 🙃

**Pull request merged**
