### PR TITLE
[LC-414] Troop ID Details

### PR DESCRIPTION
**Pull request by smurflo2**
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=voMZCoT)
# Overview

#### 🎟 Relevant Jira Issues

[LC-414](https://welibrary.atlassian.net/browse/LC-414)

#### 📚 What is the context and goal of this PR?
Add Troop ID Details view for the Troop Page

Note: History and Permissions have not been fully implemented to Figma spec, I'll circle back once we have real data to pass in. History uses old Issue History style, Permissions is hidden in this version.

#### 💡 Feature Breakdown (screenshots & videos encouraged!)
image

#### 🔍 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore (refactor, documentation update, etc)

#### 💳 Does This Create Any New Technical Debt? ( If yes, please describe and [add JIRA TODOs](https://welibrary.atlassian.net/jira/software/projects/WE/boards/2) )
- [ ] No
- [ ] Yes

# Testing

#### 🔬 How Can Someone QA This?

- Test with Troop Page PR (link incoming)

#### 🧪 Code Coverage

# Documentation

#### 📊 Storybook

# ✅ PR Checklist
- [x] Related to a Jira issue ([create one if not](https://welibrary.atlassian.net/jira/software/projects/WE/boards/2))
- [x] My code follows **style guidelines** (eslint / prettier)
- [x] I have **manually tested** common end-2-end cases
- [x] I have **reviewed** my code
- [x] I have **commented** my code, particularly where ambiguous
- [ ] New and existing **unit tests pass** locally with my changes
- [ ] I have made corresponding changes to **gitbook documentation**

### 🚀 Ready to squash-and-merge?:
- [x] Code is backwards compatible
- [x] There is **not** a "Do Not Merge" label on this PR
- [x] I have thoughtfully considered the security implications of this change.
- [x] This change does not expose new public facing endpoints that do not have authentication

### CODE REVIEW

**Review by gerardopar — CHANGES_REQUESTED** [review]
@smurflo2 things are working pretty good for me ...

small thing i ran into probably just need a max height & width + overflow hidden 

Screenshot 2024-10-28 at 12 03 49 PM

**Comment by gerardopar** [comment]
lol i posted my review on the wrong PR haha, sorry!

**Comment by gerardopar** [comment]
@smurflo2 also for the desktop styles i would set a max width of 600px & just center everything , thats the way I have it for the troop cms, so things don't stretch across

**Review by gerardopar — APPROVED** [review]

**Comment by smurflo2** [comment]
@gerardopar I don't see that image stretchiness, but I added `object-fit: contain` + overflow-hidden, so hopefully those are good now, if not I'll fix it in the follow up. Also set a max width for the footer and centered things :+1:

**Comment by smurflo2** [comment]
aaaand I also posted to the wrong PR :upside_down_face:

**Comment by smurflo2** [comment]
Closing in favor of moving TroopIdDetails directly into scouts

**Pull request closed without merging**
