### PR TITLE
Add additional options button on Boost display cards

### PR DESCRIPTION
**Pull request by goblincore**
# Overview

#### 💡 Feature Breakdown (screenshots & videos encouraged!)
This adds the dot element that triggers an onclick:

Screenshot 2023-04-24 at 4 19 21 PM

Screenshot 2023-04-24 at 4 19 19 PM

Also adjusts some of the font sizes and color of the social badge card button.

#### 🔍 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Chore (refactor, documentation update, etc)

#### 💳 Does This Create Any New Technical Debt? ( If yes, please describe and [add JIRA TODOs](https://welibrary.atlassian.net/jira/software/projects/WE/boards/2) )
- [x] No
- [ ] Yes

# Testing

#### 🧪 Code Coverage

# Documentation

#### 📊 Storybook

# ✅ PR Checklist
- [ ] Related to a Jira issue ([create one if not](https://welibrary.atlassian.net/jira/software/projects/WE/boards/2))
- [x] My code follows **style guidelines** (eslint / prettier)
- [x] I have **manually tested** common end-2-end cases
- [x] I have **reviewed** my code
- [ ] I have **commented** my code, particularly where ambiguous
- [x] New and existing **unit tests pass** locally with my changes
- [ ] I have made corresponding changes to **gitbook documentation**

### 🚀 Ready to squash-and-merge?:
- [x] Code is backwards compatible
- [x] There is **not** a "Do Not Merge" label on this PR
- [x] I have thoughtfully considered the security implications of this change.
- [x] This change does not expose new public facing endpoints that do not have authentication

### CODE REVIEW

**Review by gerardopar — APPROVED** [review]
🚀 LGTM! 

Screenshot 2023-04-24 at 1 28 23 PM



I did have a small question, probably not important .

Screen Shot 2023-04-19 at 3 43 32 PM
.. but did the button have an overlay behind it ?

**Comment by gerardopar** [comment]
kinda like the edit button here 

Screenshot 2023-04-24 at 1 29 55 PM

**Comment by goblincore** [comment]
@gerardopar oh interesting, im working of this figma and it looks like no overlay just the circle, but I can add that in later:
Screenshot 2023-04-24 at 4 37 53 PM

**Comment by gerardopar** [comment]
> @gerardopar oh interesting, im working of this figma and it looks like no overlay just the circle, but I can add that in later: Screenshot 2023-04-24 at 4 37 53 PM

@goblincore sounds good 👍🏽

**Pull request merged**
